- name: Delete a server instance
  os_server:
    cloud: "{{ cloud_name }}"
    state: absent
    name: "{{ webserver_name }}"

    #- name: Remove floating IP from a server
    #  os_floating_ip:
    #    cloud: "{{ cloud_name }}"
    #    state: absent
    #    server: "{{ webserver_name }}"
