---
- hosts: jumpbox
  gather_facts: false 
  vars:
    cloud_name: ospcloud
    deployment: dev
    #  roles:
    #    - osp-flavor
    #    - osp-securitygroup
    #    - osp-keypair
    #    - osp-network
  tasks:
    #    - name: install frontend
    - include_vars: "{{ item }}"
      with_items:
        - "host_vars/frontend1.yml"
        - "group_vars/frontends.yml"
    - include_role: 
        name: osp-securitygroup
    - include_role:
        name: osp-instance

    - include_vars: "{{ item }}"
      with_items:
        - "host_vars/app1.yml"
        - "group_vars/apps.yml"
    - include_role:
        name: osp-securitygroup
    - include_role:
        name: osp-instance

    - include_vars: "{{ item }}"
      with_items:
        - "host_vars/app2.yml"
        - "group_vars/apps.yml"
    - include_role:
        name: osp-securitygroup
    - include_role:
        name: osp-instance

    - include_vars: "{{ item }}"
      with_items:
        - "host_vars/appdb.yml"
        - "group_vars/appdbs.yml"
    - include_role:
        name: osp-securitygroup
    - include_role:
        name: osp-instance
        #    - name: install app1
        #      include_role: name=osp-securitygroup # vars_from=app1.yml
        #      include_role: name=osp-instance #vars_from=app1.yml
        #    - name: install app2
        #      include_role: name=osp-securitygroup #vars_from=app2.yml
        #      include_role: name=osp-instance #vars_from=app2.yml
        #    - name: install appdb
        #      include_role: name=osp-securitygroup #vars_from=appdb.yml
        #      include_role: name=osp-instance #vars_from=appdb.yml
        #    - name: gather facts
        #      include_role: name=osp-facts
