- os_security_group:
    cloud: "{{ cloud_name }}"
    state: present
    name: "{{ securitygroup_name }}"
    description: ICMP and SSH enabled
  tags:
    - tested
- os_security_group_rule:
    cloud: "{{ cloud_name }}"
    security_group: "{{ securitygroup_name }}"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  tags:
    - tested
- os_security_group_rule:
    cloud: "{{ cloud_name }}"
    security_group: "{{ securitygroup_name }}"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
- os_security_group_rule:
    cloud: "{{ cloud_name }}"
    security_group: "{{ securitygroup_name }}"
    protocol: icmp
    remote_ip_prefix: 0.0.0.0/0
  tags:
    - tested
