---
  - name: Fetch Instance Info
    os_server_facts:
      cloud: "{{ cloud_name }}"
      region_name: "{{ region_name }}"
    register: result
  - name: Add host to
    add_host:
      name: "{{ item.public_v4 }}"
      group: "{{ item.metadata.group }}"
    with_items: "{{result.ansible_facts.openstack_servers}}"
  - name: Add host
    add_host:
      name: "{{ item.public_v4 }}"
      group: "{{ item.metadata.deployment_name }}"
    with_items: "{{result.ansible_facts.openstack_servers}}"
