---
  - name: Install epel rpm
    yum:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      state: present     

  - name: Install python and ansible
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - python
      - python-devel
      - python-pip
      - gcc

  - name: Install shade and Upgrade ansible
    pip:
      name: "{{ item }}"
      state: latest
    with_items:
      - shade
      - ansible

  - name: mkdir /etc/openstack
    file: name=/etc/openstack state=directory

  - name: create clouds.yaml
    blockinfile:
     create: yes
     path: /etc/openstack/clouds.yaml
     block: |2
       clouds:
         ospcloud:
           auth:
             auth_url: http://192.168.0.20:5000/
             password: r3dh4t1!
             project_name: admin
             username: admin
           identity_api_version: '3.0'
           region_name: RegionOne
       ansible:
         user_hostnames: True
         expand_hostvars: False
         fail_on_errors: True
